project:
  type: website

website:
  title: "Lucas Leme"
  image: https://avatars.githubusercontent.com/u/49704353?v=4
  favicon: favicon.ico
  google-analytics: "G-6ET4F49FZC"  
  navbar:
    left: 
      - text: Posts
        href: /
      - text: Feed
        href: /feed/
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/lucas-leme-santos/
      - icon: github
        href: https://github.com/lucas-leme
  page-footer: "As informações aqui apresentadas não constituem recomendações de investimento ou aconselhamento financeiro.<br>Todo conteúdo é de caráter informativo e educacional."
  open-graph: true

format:
  html:
    theme: 
      light:
        - litera
        - styles/leme.scss
      dark:
        - cyborg
        - styles/leme.scss
    page-layout: full
    highlight-style: vs
    code-block-border-left: $blue

lang: pt-BR

execute:
  freeze: true
  warning: false

link-external-newwindow: true

# improve SEO
keywords:
  - Lucas Leme
  - Lucas Leme Santos
  - Lucas Leme Blog
  - Quant
  - Macro
  - Data Science
  - Mercado Financeiro
  - Tecnologia

pagetitle: "Lucas Leme - Blog"
description-meta: "Blog pessoal de Lucas Leme, com artigos sobre Data Science, Mercado Financeiro, Tecnologia e outros temas."
author-meta: "Analista Quant e Cientista de Dados, formado em Engenharia da Computação pela Poli-USP, com interesse em Macroeconomia, Tecnologia e Ciência de Dados."
copyright:
  holder: Lucas Leme
  year: 2023