project:
  type: website

website:
  title: "Lucas Leme"
  favicon: favicon.ico
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/lucas-leme-santos/
      - icon: github
        href: https://github.com/lucas-leme
      - icon: medium
        href: https://medium.com/@lucas_leme
  page-footer: "As informações aqui apresentadas não constituem recomendações de investimento ou aconselhamento financeiro.<br>Todo conteúdo é de caráter informativo e educacional."
  open-graph: true

format:
  html:
    theme: 
      light: litera
      dark: solar
    css: styles.css
    mainfont: Montserrat
    page-layout: full

lang: pt-BR

execute:
  freeze: auto
