project:
  type: website

website:
  title: "personal"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: materia
    css: styles.css
    mainfont: Montserrat

execute:
  freeze: auto
