project:
  type: website

website:
  title: "Lucas Leme"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/lucas-leme-santos/
      - icon: github
        text: Github
        href: https://github.com/lucas-leme
format:
  html:
    theme: materia
    css: styles.css
    mainfont: Montserrat

execute:
  freeze: auto
