project:
  type: website

website:
  title: "Lucas Leme"
  favicon: favicon.ico
  google-analytics: "G-6ET4F49FZC"
  navbar:
    left: 
      - text: Posts
        href: /
      - text: Feed
        href: /feed/
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/lucas-leme-santos/
      - icon: github
        href: https://github.com/lucas-leme
      - icon: medium
        href: https://medium.com/@lucas_leme
  page-footer: "As informações aqui apresentadas não constituem recomendações de investimento ou aconselhamento financeiro.<br>Todo conteúdo é de caráter informativo e educacional."
  open-graph: true

format:
  html:
    theme: 
      light:
        - litera
        - styles/leme.scss
      dark:
        - cyborg
        - styles/leme.scss
    page-layout: full

lang: pt-BR

execute:
  freeze: true
