---
title: "Introdução a Macroeconomia"
author: "Lucas Leme Santos"
date: "2023-10-20"
categories: [macro, pib]
toc: true
toc_sticky: true
toc_label: "Sumário"
execute:
  echo: false

draft: true
---

A Macroeconomia é uma ciência que visa estudar o comportamento da economia como um todo. Para isso, ela busca explicar o comportamento de variáveis agregadas, tanto no curto quanto no longo prazo. Uma variável agregada é aquela que representa o comportamento de um conjunto de variáveis. Por exemplo, o PIB é uma variável agregada que representa o valor total de todos os bens e serviços produzidos em uma economia.

Nesta introdução, vamos nos concentrar na composição do PIB, com ênfase no Brasil. Ao entender os componentes do PIB, podemos obter insights sobre a saúde e o desempenho geral da economia.

## Como estimar o PIB?

Existem duas principais formas de estimar o PIB: Produção Agregada e Renda.

### Produção Agregada

Através da produção agregada, é possível estimar o PIB com base em quatro componentes: Consumo, Investimento, Gastos do Governo e Exportações Líquidas. A ideia por trás dessa abordagem é que o PIB é a soma de todos os bens e serviços produzidos em uma economia. E para produzir esses bens e serviços, é necessário consumir, investir, gastar e exportar. Na equação @eq-producao_agregada, temos a representação matemática dessa abordagem.

$$
    PIB = C + I + G + (X - M)
$$ {#eq-producao_agregada}


```{python, eval=FALSE}

import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
import requests
# hide all warnings
import warnings

warnings.filterwarnings('ignore')

```

```{python, eval=FALSE}


endpoint = "https://servicodados.ibge.gov.br/api/v3/agregados/1620/periodos/199601%7C199602%7C199603%7C199604%7C199701%7C199702%7C199703%7C199704%7C199801%7C199802%7C199803%7C199804%7C199901%7C199902%7C199903%7C199904%7C200001%7C200002%7C200003%7C200004%7C200101%7C200102%7C200103%7C200104%7C200201%7C200202%7C200203%7C200204%7C200301%7C200302%7C200303%7C200304%7C200401%7C200402%7C200403%7C200404%7C200501%7C200502%7C200503%7C200504%7C200601%7C200602%7C200603%7C200604%7C200701%7C200702%7C200703%7C200704%7C200801%7C200802%7C200803%7C200804%7C200901%7C200902%7C200903%7C200904%7C201001%7C201002%7C201003%7C201004%7C201101%7C201102%7C201103%7C201104%7C201201%7C201202%7C201203%7C201204%7C201301%7C201302%7C201303%7C201304%7C201401%7C201402%7C201403%7C201404%7C201501%7C201502%7C201503%7C201504%7C201601%7C201602%7C201603%7C201604%7C201701%7C201702%7C201703%7C201704%7C201801%7C201802%7C201803%7C201804%7C201901%7C201902%7C201903%7C201904%7C202001%7C202002%7C202003%7C202004%7C202101%7C202102%7C202103%7C202104%7C202201%7C202202%7C202203%7C202204%7C202301%7C202302/variaveis/583?localidades=N1[all]&classificacao=11255[90687,90691,90696,90707,93404,93405,93406,93407,93408]"


r = requests.get(endpoint)

data = r.json()

flat_data = []
for entry in data:
    for result in entry["resultados"]:
        for serie_i in result["series"]:
            for i, date_and_value in enumerate(serie_i["serie"].items()):
                date, value = date_and_value
                format_date = date[:4] + "-" + date[4:] + "-01"

                assert len(result['classificacoes']) == 1

                flat_data.append({
                    "id": result['classificacoes'][0]['id'],
                    "nome": list(result['classificacoes'][0]['categoria'].values())[0],
                    "date": format_date,
                    "value": value
                })


# Create a DataFrame
df = pd.DataFrame(flat_data)

datasets = {
    nome: df[df["nome"] == nome]
    for nome in df["nome"].unique()
}

nomes_mapper = {
    'Agropecuária - total': 'Agropecuária',
    'Indústria - total': 'Indústria',
    'Serviços - total': 'Serviços',
    'PIB a preços de mercado': 'PIB',
    'Despesa de consumo das famílias': 'Consumo',
    'Despesa de consumo da administração pública': 'Governo',
    'Formação bruta de capital fixo': 'Investimento',
    'Exportação de bens e serviços': 'Exportação',
    'Importação de bens e serviços (-)': 'Importação'
}

datasets = {
    nomes_mapper[nome]: dataset
    for nome, dataset in datasets.items()
}

for nome, dataset in datasets.items():
    # to numeric
    dataset["value"] = pd.to_numeric(dataset["value"])
    dataset.index = pd.to_datetime(dataset["date"])

    if nome == "Importação":
        dataset["value"] = dataset["value"] * -1


product_components = [
    "Consumo",
    "Investimento",
    "Governo",
    "Exportação",
    "Importação"
]

income_components = [
    "Agropecuária",
    "Indústria",
    "Serviços"
]

product_dataset = pd.DataFrame({
    nome: dataset['value']
    for nome, dataset in datasets.items()
    if nome in product_components
})

income_dataset = {
    nome: dataset['value']
    for nome, dataset in datasets.items()
    if nome in income_components
}

```

```{python, eval=FALSE}

```


```{python, eval=FALSE}

# plot area chart

fig = px.area(product_dataset, title="Componentes do PIB - Produção Agregada")

# add PIB
fig.add_trace(
    go.Scatter(
        x=datasets["PIB"]["date"],
        y=datasets["PIB"]["value"],
        name="PIB",
        mode="lines",
        line=dict(color="black", width=2)
    ),
    row=1,
    col=1
)


fig.show()
```
