name: Update feed

on:
  schedule:
    - cron: "3,20 8,9 * * *" # every day at 8:03 and 9:20
    - cron: "31 10 * * *" # every day at 10:31
    - cron: "47 11,12 * * *" # every day at 11:47 and 12:47
    - cron: "20 15,17,18 * * *" # every day at 15:20, 17:20 and 18:20
    - cron: "30 22,23 * * *" # every day at 22:30 and 23:30
  # workflow_dispatch: # run manually
  #   inputs:
  #     logLevel:
  #       description: "Manual test"
  #       required: false
  #       default: "Test"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # install the python version needed

      - name: install feed reqs
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_feed.txt

      - name: execute py script # run main.py
        run: python feed/update_feed.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add feed/feed.yaml
          git diff-index --quiet HEAD || (git commit -a -m "Update feed database" --allow-empty)

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python and Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - run: pip install jupyter
      - run: pip install -r requirements.txt

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
